### ISSUE TITLE
Add to watch to allow watching multiple job sets

### ISSUE THREAD

**Issue by JamesMurkin** [armadaproject/armada#162]
**Problem**
If you run a load test with multiple jobsets. 

The loadtest will watch these multiple jobsets.
 
However there is no way to stop/restart this watching of multiple jobsets. meaning you have to leave it running and/or can't rewatch an experiment how it happened.

**Suggested solution**
- Armadactl watch should be updated to support watching multiple jobsets 
- armada-load-tester should be updated to support watching multiple jobsets (potentially on multiple connections, as is the case in loadtest)

**Comment by itamarst** [comment]
I can try to do this.

**Comment by itamarst** [comment]
Is the second bullet item actually necessary? The YAML at least supports multiple jobs?

**Comment by jankaspar** [comment]
Hi, thanks for picking this up. Lets worry just about the armadactl here, forgot about the load tester, it does not need updating right now.
There is support for watching multiple streams in Redis which we want to leverage to watch multiple job sets instead of opening multiple connections.
The implementation should change api to accept multiple job set ids, propagate that to `ReadEvents` of `RedisEventRepository` (https://github.com/G-Research/armada/blob/master/internal/armada/repository/event.go#L67) and call XREAD (https://redis.io/commands/xread) with multiple stream ids.

**Comment by itamarst** [comment]
OK, you can review #285 then, since it covers just the armadactl bit I think.
