### ISSUE TITLE
Add comments to functions to make code easier to understand

### ISSUE THREAD

**Issue by Chinwendu20** [armadaproject/armada#2190]
Some functions in the codebase have no commands. Adding comments would help make the code easier ton understand and save developers the stress on having to navigate to those functions to understand what they are actually doing.

**Comment by dave-gantenbein** [comment]
While there's nothing wrong with a comment per se, a robust set of tests is a much more valuable way of documenting how a function is to be used. Since the code base is vast, the scope of this ticket is too large as well. Let's instead open tickets for adding or extending tests to individual structs or methods. Thanks!

**Comment by Chinwendu20** [comment]
Thanks a lot, I took a queue from this issue https://github.com/armadaproject/armada/issues/2167 which happens to have a large scope as well. It also addresses the tests you mentioned. Comments are great because during code navigation using an ide like goland for example, I can easily see what a function is about by hovering around it.
