### ISSUE TITLE
Design part of our website has two different pages

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2529]
**Describe the bug**

If you browse to https://armadaproject.io/design/ you can see the relationships doc that @Sharpz7 added.  

But if you click design via website (https://armadaproject.io/design), it will not have the relationships doc.  

**Files Or Markdown that can reproduce the issue**

**Expected behavior**
I would expect that we should have https://armadaproject.io/design/ behavior in both cases.  

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-323) by [Unito](https://www.unito.io)

**Comment by JosephHuntley** [comment]
I have identified the issue as file routing. When accessing the URL https://armadaproject.io/design, it fetches [design.md](https://github.com/armadaproject/armada/blob/gh-pages/design.md), whereas https://armadaproject.io/design/ fetches [design/index.md](https://github.com/armadaproject/armada/blob/gh-pages/design/index.md). This discrepancy occurs because the browser interprets the trailing slash in the URL as the 'index' page.

An optimal solution would be to set up a redirect from https://armadaproject.io/design to https://armadaproject.io/design/ and remove design.md since this wouldn't break any links relying on https://armadaproject.io/design while also creating only a single file to update whenever changes occur. A sub-optimal fix would be to update design.md. However, this would lead to both files needing to be maintained whenever an update occurs. 

As this is my first contribution to the project, I'm unsure about the underlying technology that controls routing. I would appreciate guidance on how to implement a fix to address this file routing issue.

Thank you for your assistance.

**Comment by dave-gantenbein** [comment]
Hi @JosephHuntley! The underlying technology is Github pages, and they are served from their own branch: gh-pages.

Hope that helps.

**Comment by ShivangShandilya** [comment]
@JosephHuntley are you working on this issue? If not, I would like to work on it.

**Comment by kirtanchandak** [comment]
Hey if anyone is not workin on this issue can I take this @kannon92, assign it to me!

**Comment by arssshhhk** [comment]
@ShivangShandilya are you working on this issue? if not, I would like to work on it.

**Comment by ShivangShandilya** [comment]
Yup mate I'll be done with this soon, been busy with my GSoC project. If I'm not able to do this I'll surely pass on this to you

**Comment by Sharpz7** [comment]
@ShivangShandilya Any update?

**Comment by ShivangShandilya** [comment]
> @ShivangShandilya Any update?

Yeah right so I proposed that I might have found the solution for this before to Kevin. It was this:
While inspecting I found the code to be here but if you open the same which is located in header.html file under _includes directory the code to display design is not there so maybe website automatically fetches the design.md file instead of one in index directory.

**Comment by Sharpz7** [comment]
@ShivangShandilya Nice spot! Feel free to make the PR

**Comment by Rhythm-26** [comment]
Can we close this issues? it seems we already have the fix merged
