### ISSUE TITLE
Documentation Error: INSTALLATION FAILED: must either provide a name or specify --generate-name

### ISSUE THREAD

**Issue by jjkoehorst** [armadaproject/armada#2715]
I am working on a remote test cluster where I want to follow the "production" documentation to test a (test) production environment.

The helm setup at https://armadaproject.io/production-install

> export ARMADA_VERSION=v0.3.84 
> helm install ./deployment/armada --set image.tag=$ARMADA_VERSION -f ./server-values.yaml

Results in a 

> Error: INSTALLATION FAILED: must either provide a name or specify --generate-name

I also have difficulties with installing the recommended prerequisites such as https://github.com/helm/charts/tree/master/stable/redis-ha which has been deprecated for more than a year now...

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-501) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
@jjkoehorst I'm sorry you are dealing with this.  I noticed that that file needs some love.  I created https://github.com/armadaproject/armada/issues/2736 to reflect that we want to shift our deployments to use `armada-operator` rather than the individual helm charts.  

Please feel free to open up a PR to fix the issues you see right now.  I think you could use bitnami redis chart rather than the one you linked above.

**Comment by richscott** [comment]
Closing, Operator is preferred installation tooling.
