### ISSUE TITLE
Improve cacheability in Python client builds

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#3105]
The `python-client.yml` workflow runs the Mage target `test2epython`, which does a build of the python-client Docker image each time, then runs it. Can the built image be cached?

Tasks:
- [x] using the cached tools (because of the mage target and it's dependencies that need the tools)
- [ ] set up image for caching

**Comment by pavlovic-ivan** [comment]
Looks like this issue will have two parts. One part is using the cached tools (because of the mage target and it's dependencies that need the tools), and the other one is the image. So i suggest either adding two checkboxes to the description, so we can visualise this, and then i will link the PRs that resolve this. 

Currently in progress is restoring the cached tools for the jobs in Python client workflow (so, part 1 of my sugesstion above)

**Comment by richscott** [comment]
@pavlovic-ivan Task list with two items added to the description - feel free to adjust/fix the wording.

**Comment by pavlovic-ivan** [comment]
@richscott thank you!

**Comment by pavlovic-ivan** [comment]
PR for this issue: https://github.com/armadaproject/armada/pull/3244

**Comment by pavlovic-ivan** [comment]
Hi @richscott. I did investigate the task #2 here. Caching the docker layers will reduce the job by ~1m, but will add additional caches to Github actions, which will hit the 10GB limit at some point. Are you ok with closing this entirely? 

FYI: @dave-gantenbein

**Comment by richscott** [comment]
I agree - marking this as done - great work!

**Comment by pavlovic-ivan** [comment]
Thanks!
